# Generated by Django 4.0.4 on 2022-05-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('time_in_air', models.CharField(default='-', max_length=15, verbose_name='time_in_air')),
            ],
        ),
        migrations.CreateModel(
            name='Glider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='name')),
                ('time_in_air', models.CharField(default='-', max_length=15, verbose_name='time_in_air')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=30, verbose_name='lastname')),
                ('instructor', models.BooleanField(default=False, verbose_name='instructor')),
                ('winch_operator', models.BooleanField(default=False, verbose_name='winch_operator')),
                ('glider_pilot', models.BooleanField(default=False, verbose_name='glider_pilot')),
                ('airplane_pilot', models.BooleanField(default=False, verbose_name='airplane_pilot')),
            ],
        ),
        migrations.CreateModel(
            name='Chronometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_start', models.DateTimeField(verbose_name='time_of_start')),
                ('glider_landing_time', models.DateTimeField(verbose_name='glider_landing_time')),
                ('airplane_landing_time', models.DateTimeField(verbose_name='airplane_landing_time')),
                ('glider_tia', models.CharField(default='-', max_length=15, verbose_name='glider_tia')),
                ('airplane_tia', models.CharField(default='-', max_length=15, verbose_name='glider_tia')),
                ('start_type', models.CharField(max_length=1, verbose_name='start_type')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='airplane_missions', to='echrono.airplane')),
                ('glider_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='missions', to='echrono.glider')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instructor_flights', to='echrono.user')),
                ('pilot_passenger_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='flights', to='echrono.user')),
                ('tow_pilot_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tows', to='echrono.user')),
                ('winch_operator_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='launches', to='echrono.user')),
            ],
        ),
        migrations.CreateModel(
            name='AirplaneFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_start', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.airplane')),
                ('airplane_pilot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.user')),
            ],
        ),
    ]
