# Generated by Django 4.0.4 on 2022-06-14 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echrono', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('fill_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GliderTechnicalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('wings_check', models.BooleanField(default=False)),
                ('fuselage_check', models.BooleanField(default=False)),
                ('sheathing_check', models.BooleanField(default=False)),
                ('glider_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed_airplane', to='echrono.glider')),
                ('inspector_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ginspector', to='echrono.user')),
            ],
        ),
        migrations.CreateModel(
            name='FuelTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('aircraft_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fueled_airplane', to='echrono.airplane')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer', to='echrono.user')),
                ('fuel_pod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed_airplane', to='echrono.fuelpods')),
            ],
        ),
        migrations.CreateModel(
            name='AirplaneTechnicalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('engine_check', models.BooleanField()),
                ('fuselage_check', models.BooleanField()),
                ('sheathing_check', models.BooleanField()),
                ('airplane_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed_airplane', to='echrono.airplane')),
                ('inspector_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inspector', to='echrono.user')),
            ],
        ),
    ]
