# Generated by Django 4.0.4 on 2022-06-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echrono', '0002_fuelpods_glidertechnicalreview_fueltransactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inspector',
            field=models.BooleanField(default=False, verbose_name='inspector'),
        ),
        migrations.AlterField(
            model_name='airplanetechnicalreview',
            name='inspector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='airplaneinspector', to='echrono.user'),
        ),
        migrations.AlterField(
            model_name='glidertechnicalreview',
            name='inspector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gliderinspector', to='echrono.user'),
        ),
    ]
