# Generated by Django 4.0.4 on 2022-06-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echrono', '0003_user_inspector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelpods',
            name='fill_percentage',
            field=models.IntegerField(default=100),
        ),
    ]
