# Generated by Django 4.0.4 on 2022-06-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echrono', '0005_alter_chronometer_airplane_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplanetechnicalreview',
            name='airplane_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.airplane'),
        ),
        migrations.AlterField(
            model_name='airplanetechnicalreview',
            name='inspector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.user'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='airplane_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.airplane'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='glider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.glider'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='instructor_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='instruct', to='echrono.user'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='pilot_passenger_id',
            field=models.ForeignKey(default='pilot', on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.user'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='tow_pilot_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='tow', to='echrono.user'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='winch_operator_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='winch', to='echrono.user'),
        ),
        migrations.AlterField(
            model_name='fueltransactions',
            name='aircraft_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.airplane'),
        ),
        migrations.AlterField(
            model_name='fueltransactions',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.user'),
        ),
        migrations.AlterField(
            model_name='fueltransactions',
            name='fuel_pod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.fuelpods'),
        ),
        migrations.AlterField(
            model_name='glidertechnicalreview',
            name='glider_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.glider'),
        ),
        migrations.AlterField(
            model_name='glidertechnicalreview',
            name='inspector_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='echrono.user'),
        ),
    ]
