# Generated by Django 4.0.4 on 2022-06-16 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echrono', '0006_alter_airplanetechnicalreview_airplane_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fueltransactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 16, 12, 31, 47, 152423)),
        ),
    ]
