# Generated by Django 4.0.4 on 2022-06-19 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echrono', '0008_alter_chronometer_airplane_landing_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronometer',
            name='airplane_landing_time',
            field=models.DateTimeField(null=True, verbose_name='airplane_landing_time'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='airplane_tia',
            field=models.CharField(default='-', max_length=15, null=True, verbose_name='glider_tia'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='glider_landing_time',
            field=models.DateTimeField(null=True, verbose_name='glider_landing_time'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='glider_tia',
            field=models.CharField(default='-', max_length=15, null=True, verbose_name='glider_tia'),
        ),
        migrations.AlterField(
            model_name='chronometer',
            name='time_of_start',
            field=models.DateTimeField(null=True, verbose_name='time_of_start'),
        ),
        migrations.AlterField(
            model_name='fueltransactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 20, 22, 57, 156107)),
        ),
    ]
